export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';

export const ADD_ANSWER = 'ADD_ANSWER';
export const DELETE_ANSWER = 'DELETE_ANSWER';

export const ADD_READING_QUESTION = 'ADD_READING_QUESTION';
export const DELETE_READING_QUESTION = 'DELETE_READING_QUESTION';

export const SET_QUESTION_TYPE = 'SET_QUESTION_TYPE';
export const SET_READING_TEXT = 'SET_READING_TEXT';

export const SET_SECTIONS = 'SET_SECTIONS';

export const CREATE_TEST_REQUEST = 'CREATE_TEST_REQUEST';
export const CREATE_TEST_SUCCESSFUL = 'CREATE_TEST_SUCCESSFUL';
export const CREATE_TEST_FAILURE = 'CREATE_TEST_FAILURE';

export const SET_TEST_TITLE = 'SET_TEST_TITLE';
export const SET_TEST_DESCRIPTION = 'SET_TEST_DESCRIPTION';
export const SET_TEST_SECTION = 'SET_TEST_SECTION';
export const SET_TEST_TIME_LIMIT = 'SET_TEST_TIME_LIMIT';
export const SET_TEST_RATE = 'SET_TEST_RATE';
export const SET_TEST_RETAKE_TIMEOUT = 'SET_TEST_RETAKE_TIMEOUT';

export const SET_TEST_DATA = 'SET_TEST_DATA';

export const SET_QUESTION_DATA = 'SET_QUESTION_DATA';

export const SET_COURSE_ID = 'SET_COURSE_ID';

export const MERGE_TEST_DATA = 'MERGE_TEST_DATA';

export const EDIT_QUESTION = 'EDIT_QUESTION';

export const FETCH_EDIT_QUESTION = 'FETCH_EDIT_QUESTION';