export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST';
export const ADD_QUESTION_SUCCESSFUL = 'ADD_QUESTION_SUCCESSFUL';
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE';
export const DELETE_QUESTION_REQUEST = 'DELETE_QUESTION_REQUEST';
export const DELETE_QUESTION_SUCCESSFUL = 'DELETE_QUESTION_SUCCESSFUL';
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE';

export const SET_QUESTION_TYPE = 'SET_QUESTION_TYPE';
