export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';

export const ADD_ANSWER = 'ADD_ANSWER';
export const DELETE_ANSWER = 'DELETE_ANSWER';

export const ADD_READING_QUESTION = 'ADD_READING_QUESTION';
export const DELETE_READING_QUESTION = 'DELETE_READING_QUESTION';

export const SET_QUESTION_TYPE = 'SET_QUESTION_TYPE';
export const SET_READING_TEXT = 'SET_READING_TEXT';

export const SET_SECTIONS = 'SET_SECTIONS';

